"""empty message

Revision ID: 48b3599c4fbb
Revises: a6a599d2b343
Create Date: 2025-03-24 20:26:32.980659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b3599c4fbb'
down_revision = 'a6a599d2b343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('sos_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('sos_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
