"""empty message

Revision ID: 5e185658b41c
Revises: 50abe6f398ea
Create Date: 2025-04-04 19:16:20.094322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e185658b41c'
down_revision = '50abe6f398ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animalshelter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('coordinates', sa.Float(), nullable=True))

    with op.batch_alter_table('veterinary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('coordinates', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veterinary', schema=None) as batch_op:
        batch_op.drop_column('coordinates')
        batch_op.drop_column('img_url')

    with op.batch_alter_table('animalshelter', schema=None) as batch_op:
        batch_op.drop_column('coordinates')
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###
