"""empty message

Revision ID: 78c764883dfe
Revises: 9e7bbefc62e2
Create Date: 2025-03-26 14:00:47.220176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78c764883dfe'
down_revision = '9e7bbefc62e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor_amount', sa.Float(), nullable=True))
        batch_op.drop_column('donor_ammount')

    with op.batch_alter_table('soscases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_amount', sa.Float(), nullable=True))
        batch_op.drop_column('pending_ammount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soscases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_ammount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('pending_amount')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor_ammount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('donor_amount')

    # ### end Alembic commands ###
