"""empty message

Revision ID: 9e7bbefc62e2
Revises: 0b11840a55b0
Create Date: 2025-03-26 13:58:47.109618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e7bbefc62e2'
down_revision = '0b11840a55b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donor_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('donor_ammount', sa.Float(), nullable=True))
        batch_op.drop_column('donnor_ammount')
        batch_op.drop_column('donnor_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donnor_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('donnor_ammount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('donor_ammount')
        batch_op.drop_column('donor_name')

    # ### end Alembic commands ###
