"""empty message

Revision ID: 9fbb52f05e67
Revises: 56ed0296bc69
Create Date: 2025-04-07 13:49:21.941697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fbb52f05e67'
down_revision = '56ed0296bc69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoptions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('Adopted :)', 'Waiting for you <3', 'Adoption in process', 'Recently rescued', name='status_enum'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoptions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('Adopted :)', 'Waiting for you <3', 'Adoption in process', 'Recently rescued', name='status_enum'),
               nullable=True)

    # ### end Alembic commands ###
