"""empty message

Revision ID: ec4ad251d732
Revises: 
Create Date: 2025-03-25 14:14:00.050750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4ad251d732'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('services', sa.String(length=200), nullable=True),
    sa.Column('opening_hours', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', 'veterinary', 'protector', name='role'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('adoptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Adopted :)', 'Waiting for you <3', 'Adoption in process', 'Recently rescued', name='status'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('how_old', sa.Integer(), nullable=True),
    sa.Column('specie', sa.Enum('Dog', 'Cat', 'Other', name='specie'), nullable=True),
    sa.Column('race', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.Enum('Male', 'Female', name='sex'), nullable=False),
    sa.Column('unadopted_time', sa.DateTime(), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('img_url', sa.String(length=255), nullable=True),
    sa.Column('adoption_priority', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('importance_level', sa.Enum('low', 'medium', 'high', name='importance_level'), nullable=True),
    sa.Column('img_url', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soscases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('specie', sa.Enum('Dog', 'Cat', 'Other', name='species_enum'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Served', 'Waiting for help', name='status_enum'), nullable=True),
    sa.Column('operation_cost', sa.Float(), nullable=True),
    sa.Column('pending_ammount', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_date', sa.DateTime(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('donnor_name', sa.String(length=100), nullable=True),
    sa.Column('donnor_ammount', sa.Float(), nullable=True),
    sa.Column('sos_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sos_id'], ['soscases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donations')
    op.drop_table('soscases')
    op.drop_table('news')
    op.drop_table('adoptions')
    op.drop_table('users')
    # ### end Alembic commands ###
